### ISSUE TITLE
what is correct configuration for symfony5

### ISSUE THREAD

**Issue by ghost** [Haehnchen/idea-php-symfony2-plugin#1417] opened 2020-01-04 21:08 UTC
Hi, I'm using phpStorm just for few weeks and I don't know where else to ask :) 
What is correct configuration for symfony5?
by default there is 
```
*Translation Root Path: app/cache/dev/translations*
*App Directory: app*
*Web Directory: web* 
```
but it looks like old symfony... Should I change it to something like this?
```
*Translation Root Path: translations*
*App Directory: src*
*Web Directory: public* 
```
It's bit confusing. Can somebody add little guide to plugin documentation? :) :)

**Comment by Tobion** [comment] 2020-05-12 11:39
Duplicate of #1148

**Comment by Haehnchen** [comment] 2022-05-04 19:13
i changed but there is also much more guessing during runtime, all default file structure are supported out the box, no need for a value change here. there will be UI improvements.

- eg "*App Directory: src*" is already something different or not needed

**Closed by Haehnchen** 2022-05-04 19:13 UTC
