### ISSUE TITLE
Create service in YAML format should use space instead of tab

### ISSUE THREAD

**Issue by leo108** [Haehnchen/idea-php-symfony2-plugin#736] opened 2016-05-25 01:34 UTC
It's recommended to use `space` instead of `tab` in YAML format

**Comment by veloxy** [comment] 2016-09-02 08:23
I agree, it's stated in the [Symfony docs](http://symfony.com/doc/current/components/yaml/yaml_format.html) to always use spaces:

>There is one important thing you need to remember when using indentation in a YAML file: Indentation must be done with one or more spaces, but never with tabulators.

**Comment by veloxy** [comment] 2016-09-02 08:28
Also, this is a duplicate of #533

**Comment by Haehnchen** [comment] 2017-06-11 11:28
done

**Closed by Haehnchen** 2017-06-11 11:28 UTC
