### ISSUE TITLE
The service generator generates YAML with tabs

### ISSUE THREAD

**Issue by Azenet** [Haehnchen/idea-php-symfony2-plugin#533] opened 2015-06-22 15:48 UTC
When generating a service, generating a definition for a service in YAML generates a YAML snippet that contains tabs, if you copy it to the clipboard and then paste it.

**Comment by Haehnchen** [comment] 2015-06-28 07:39
duplicate by #374 will fixed with #362

**Comment by Jean85** [comment] 2016-03-03 08:54
Up, the problem is still here :( and I don't see it mentioned in #362
Also, #347 is kinda unrelated, XML has different indentation rules and doesn't break because of indentation.

**Comment by Haehnchen** [comment] 2017-06-11 11:27
done

**Closed by Haehnchen** 2017-06-11 11:27 UTC
Labels: todo
