### ISSUE TITLE
Getting java.lang.StackOverflowError from time to time

### ISSUE THREAD

**Issue by felixgeyer** [Haehnchen/idea-php-symfony2-plugin#1565] opened 2020-12-11 17:01 UTC
Hi there,

from time to time, I'm experiencing a `java.lang.StackOverflowError` error in PHPStorm.
If this occurs, IDE auto completion for our Codeception test suite is broken. PHPStorm still recognizes the class methods, as they're still clickable.
Our regular project is not affected by this. Auto completion still works there.

According to the stacktrace this looks like a bad recursion.

**PHPStorm version**: 2020.3
**Plugin version:** 0.21.204

**Stacktraces:**
```
java.lang.StackOverflowError
	at com.intellij.openapi.util.UserDataHolderBase.getUserData(UserDataHolderBase.java:45)
	at com.intellij.openapi.util.NotNullLazyKey.getValue(NotNullLazyKey.java:21)
	at com.intellij.openapi.project.DumbService.getInstance(DumbService.java:188)
	at com.intellij.openapi.project.DumbService.isDumb(DumbService.java:59)
	at com.jetbrains.php.PhpIndexImpl.shouldUseSlowResolve(PhpIndexImpl.java:299)
	at com.jetbrains.php.PhpIndexImpl.getByFQN(PhpIndexImpl.java:895)
	at com.jetbrains.php.PhpIndexImpl.getClassesByFQNInternal(PhpIndexImpl.java:975)
	at com.jetbrains.php.PhpIndexImpl.getClassesByFQN(PhpIndexImpl.java:968)
	at com.jetbrains.php.PhpClassHierarchyUtils.getSuperClasses(PhpClassHierarchyUtils.java:416)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getSuperClass(PhpClassImpl.java:393)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.getImplementedMethods(PhpElementsUtil.java:598)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.getImplementedMethods(PhpElementsUtil.java:598)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.getImplementedMethods(PhpElementsUtil.java:598)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.getImplementedMethods(PhpElementsUtil.java:598)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.getImplementedMethods(PhpElementsUtil.java:598)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.getImplementedMethods(PhpElementsUtil.java:598)
	...
```

```
java.lang.StackOverflowError
	at com.intellij.psi.impl.source.SubstrateRef$StubRef.isValid(SubstrateRef.java:128)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.isValid(StubBasedPsiElementBase.java:258)
	at com.intellij.psi.impl.source.SubstrateRef$StubRef.isValid(SubstrateRef.java:134)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.isValid(StubBasedPsiElementBase.java:258)
	at com.intellij.psi.impl.PsiCachedValue.getTimeStamp(PsiCachedValue.java:123)
	at com.intellij.util.CachedValueBase.isDependencyOutOfDate(CachedValueBase.java:120)
	at com.intellij.psi.impl.PsiCachedValue.isDependencyOutOfDate(PsiCachedValue.java:112)
	at com.intellij.util.CachedValueBase.isUpToDate(CachedValueBase.java:110)
	at com.intellij.psi.impl.PsiCachedValue.isUpToDate(PsiCachedValue.java:106)
	at com.intellij.util.CachedValueBase.getUpToDateOrNull(CachedValueBase.java:92)
	at com.intellij.psi.impl.PsiCachedValueImpl.getUpToDateOrNull(PsiCachedValueImpl.java:28)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:144)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:120)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getOwnMethodsMap(PhpClassImpl.java:320)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getOwnMethods(PhpClassImpl.java:309)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.getImplementedMethods(PhpElementsUtil.java:587)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.getImplementedMethods(PhpElementsUtil.java:598)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.getImplementedMethods(PhpElementsUtil.java:598)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.getImplementedMethods(PhpElementsUtil.java:598)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.getImplementedMethods(PhpElementsUtil.java:598)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.getImplementedMethods(PhpElementsUtil.java:598)
       ...
```

```
java.lang.StackOverflowError
	at com.intellij.serviceContainer.ComponentManagerImpl$Companion.isLightService(ComponentManagerImpl.kt:69)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:446)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:440)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:25)
	at com.jetbrains.php.lang.classAlias.PhpClassAliasIndex.getInstance(PhpClassAliasIndex.java:43)
	at com.jetbrains.php.PhpIndexImpl.getAliasesByName(PhpIndexImpl.java:934)
	at com.jetbrains.php.PhpIndexImpl.addAliases(PhpIndexImpl.java:988)
	at com.jetbrains.php.PhpIndexImpl.getClassesByFQN(PhpIndexImpl.java:969)
	at com.jetbrains.php.PhpClassHierarchyUtils.getSuperClasses(PhpClassHierarchyUtils.java:416)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getSuperClass(PhpClassImpl.java:393)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.getImplementedMethods(PhpElementsUtil.java:598)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.getImplementedMethods(PhpElementsUtil.java:598)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.getImplementedMethods(PhpElementsUtil.java:598)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.getImplementedMethods(PhpElementsUtil.java:598)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.getImplementedMethods(PhpElementsUtil.java:598)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.getImplementedMethods(PhpElementsUtil.java:598)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.getImplementedMethods(PhpElementsUtil.java:598)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.getImplementedMethods(PhpElementsUtil.java:598)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.getImplementedMethods(PhpElementsUtil.java:598)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.getImplementedMethods(PhpElementsUtil.java:598)
        ...
```

**Comment by maksimovichd** [comment] 2020-12-23 22:53
me too

`com.intellij.diagnostic.PluginException: Reference element is not the same element for which references were queried [Plugin: fr.adrienbrault.idea.symfony2plugin]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:335)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:59)
	at com.intellij.diagnostic.PluginException.logPluginError(PluginException.java:76)
	at com.intellij.psi.PsiReferenceServiceImpl.assertReferencesHaveSameElement(PsiReferenceServiceImpl.java:55)
	at com.intellij.psi.PsiReferenceServiceImpl.getReferences(PsiReferenceServiceImpl.java:28)
	at com.intellij.psi.search.SingleTargetRequestResultProcessor.processTextOccurrence(SingleTargetRequestResultProcessor.java:32)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$5.lambda$execute$0(PsiSearchHelperImpl.java:948)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processTreeUp(LowLevelSearchUtil.java:88)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.lambda$processElementsAtOffsets$0(LowLevelSearchUtil.java:179)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processOffsets(LowLevelSearchUtil.java:205)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsAtOffsets(LowLevelSearchUtil.java:178)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$5.execute(PsiSearchHelperImpl.java:944)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:280)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:271)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:25)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:885)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:25)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processCandidates$18(PsiSearchHelperImpl.java:905)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processVirtualFile$11(PsiSearchHelperImpl.java:543)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.openapi.application.ex.ApplicationUtil.tryRunReadAction(ApplicationUtil.java:33)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processVirtualFile(PsiSearchHelperImpl.java:525)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processPsiFileRoots$7(PsiSearchHelperImpl.java:400)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processFilesConcurrentlyDespiteWriteActions$8(PsiSearchHelperImpl.java:473)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processFilesConcurrentlyDespiteWriteActions$9(PsiSearchHelperImpl.java:472)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:86)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Element: com.intellij.psi.impl.source.xml.XmlTokenImpl; reference: fr.adrienbrault.idea.symfony2plugin.config.xml.ParameterXmlReference; reference element: com.intellij.psi.impl.source.xml.XmlTextImpl
	at com.intellij.psi.PsiReferenceServiceImpl.assertReferencesHaveSameElement(PsiReferenceServiceImpl.java:65)
	... 38 more`

**Comment by faso-dev** [comment] 2021-01-07 11:50
me too

**Comment by adamwojs** [comment] 2021-04-18 12:34
@Haehnchen This issue seems to be duplicate of https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/1599 and which was fixed by https://github.com/Haehnchen/idea-php-symfony2-plugin/pull/1609.

**Closed** 2021-12-15 18:22 UTC
