### ISSUE TITLE
plugin not working in PhpStorm 2018.3 EAP

### ISSUE THREAD

**Issue by bosske1** [Haehnchen/idea-php-symfony2-plugin#1226] opened 2018-09-07 15:28 UTC
After updating the PhpStorm to the latest version (2018.3 EAP), the plugin is disabled and can not be enabled.

PhpStorm 2018.3 EAP
Build #PS-183.2153.44
Symfony Plugin: 0.16.165

**Comment by jacquesbh** [comment] 2018-09-09 09:30
During the wait, you can still download a previous version of PHPStorm here: https://confluence.jetbrains.com/display/PhpStorm/Previous+PhpStorm+Releases

**Comment by mablae** [comment] 2018-09-11 00:30
I was able to build a version with these changes (At least I could install the the ZIP and no errors thrown, seems to work): 

```diff
diff --git a/gradle.properties b/gradle.properties
index 285e7a15..d7dc1f5f 100644
--- a/gradle.properties
+++ b/gradle.properties
@@ -1,6 +1,6 @@
-ideaVersion = IU-2018.2
-phpPluginVersion = 182.3684.42
-twigPluginVersion = 182.3458.35
+ideaVersion = IU-183.2153.8
+phpPluginVersion = 183.2153.44
+twigPluginVersion = 183.2153.44
 toolboxPluginVersion = 0.4.6
 annotationPluginVersion = 5.3

```

**Comment by mablae** [comment] 2018-09-11 00:31
I picked the php and twig versions directly from the current IDE version I had installed. 

Is this the correct way to go?

**Comment by cedricziel** [comment] 2018-09-11 06:37
The problem is, the current release doesnt incorporate any of the latest changes. - Yes, but it should even work with the default properties-file, @mablae .

@Haehnchen can we have a new release, please :)

**Comment by mablae** [comment] 2018-09-11 15:12
@cedricziel I quickly looked up breaking changes and grepped the code. There is only one BC listed ATM: https://www.jetbrains.org/intellij/sdk/docs/reference_guide/api_changes/api_changes_list_2018.html

**Comment by cedricziel** [comment] 2018-09-11 17:20
@bosske1 mentioned the plugin could not be enabled - that's much about a faulty `until` constraint.

I'll add a 2018.3 build to the matrix.

**Comment by cedricziel** [comment] 2018-09-11 18:52
Well - it works with 2018.3 indeed (#1228). - It's not the plugin itself, it's the missing release, since all real shortcomings (that were detected by tests) are fixed in the current master.

**Closed** 2018-09-12 16:26 UTC
