### ISSUE TITLE
Form method can not automatically prompt

### ISSUE THREAD

**Issue by Jackson8Zhang** [Haehnchen/idea-php-symfony2-plugin#951] opened 2017-06-09 10:43 UTC
Phpstorm 2017.1.4
php7
Symfony3.3

![2017-06-09](https://user-images.githubusercontent.com/25034767/26972033-745e3ef2-4cd5-11e7-98a2-579a4beb6e09.png)

**Comment by Haehnchen** [comment] 2017-07-06 15:38
duplicate of https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/863 to be fixed with PhpStorm 2017.2 release

**Closed by Haehnchen** 2017-07-06 15:38 UTC
