### ISSUE TITLE
Issue in Symfony Support in PhpStorm (0.23.210)

### ISSUE THREAD

**Issue by flashy86** [Haehnchen/idea-php-symfony2-plugin#1688] opened 2021-08-10 14:39 UTC
java.nio.file.InvalidPathException: Illegal char <:> at index 17: [flashy86] diff@C:/[...]/PhpstormProjects/sortir/src/Controller/ParticipantController.php
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at fr.adrienbrault.idea.symfony2plugin.stubs.ServiceIndexUtil.isMatchingGlobResource(ServiceIndexUtil.java:304)
	at fr.adrienbrault.idea.symfony2plugin.stubs.ServiceIndexUtil.matchesResourcesGlob(ServiceIndexUtil.java:203)
	at fr.adrienbrault.idea.symfony2plugin.stubs.ServiceIndexUtil.findServiceDefinitionsOfResourceLazy(ServiceIndexUtil.java:275)
	at fr.adrienbrault.idea.symfony2plugin.config.ServiceLineMarkerProvider.classNameMarker(ServiceLineMarkerProvider.java:129)
	at fr.adrienbrault.idea.symfony2plugin.config.ServiceLineMarkerProvider.collectSlowLineMarkers(ServiceLineMarkerProvider.java:76)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:185)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:82)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:81)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:77)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:399)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:391)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:367)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:365)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by flashy86** [comment] 2021-08-10 14:40
This is the fatal error message i have everyday. What can I do?

**Comment by arnowelzel** [comment] 2021-08-13 10:34
This seems to be a duplicate of #1680.

I don't think, that we can do anything to avoid this - this needs to be fixed in the plugin. However my knowledge about the interna of plugins in PHPStorm is not good enough to help here, sorry.

**Comment by Haehnchen** [comment] 2022-05-04 17:51
> at fr.adrienbrault.idea.symfony2plugin.stubs.ServiceIndexUtil.isMatchingGlobResource(ServiceIndexUtil.java:304)

`} catch (PatternSyntaxException | InvalidPathException e) {`

checked; was already fixed

**Closed by Haehnchen** 2022-05-04 17:51 UTC
