### ISSUE TITLE
Twig: Missing Template

### ISSUE THREAD

**Issue by pierma67** [Haehnchen/idea-php-symfony2-plugin#1000] opened 2017-08-15 11:12 UTC
(sorry, I searched about this but I found similar issues but without solution)
This code in a Controller:
  /**
   * @Route("/edit/{id}", requirements={"id"="\d+"}, name="categoria_edit");
   * @Template()
   */
  public function editAction($id, Request $request)
  {
gives me the message "Missing Template" but edit.html.twig does exist and if I try to follow the proposed action it asks me to create a template named ed.html.twig.

**Comment by pierma67** [comment] 2017-08-15 11:18
(I add: all other templates in the same controller solve to correct names - also, if I rename my edit.html.twig template to ed.html.twig Symfony plugin stops complaining but, obviously, application stops working as the correctly named template is not found)

**Comment by goedderz** [comment] 2017-08-17 09:49
I've got the same issue with an action named `latestBalanceSheetAction`. The proposed action would like to create `latestBalanceShee.html.twig` (with a missing `t`). I tested a bit and found that `latestBalanceSheetFooBarAction` results in the expected `latestBalanceSheetFooBar.html.twig`, while `latestBalanceSheetFooAction` results in `latestBalanceSheetF.html.twig`.

**Comment by goedderz** [comment] 2017-08-18 07:04
This looks like a duplicate of #999

**Comment by Haehnchen** [comment] 2017-09-06 16:19
done

**Closed** 2017-09-17 09:41 UTC
Labels: fixed
